version: '3.8'

services:
  # 1. Qdrant (Vector Database)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_doan  # Tên container cho Qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped


